#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
# Python
#
# See: http://platform-guild.readthedocs.io/en/latest/language-guides/python/development.html
#

export PYTHONDONTWRITEBYTECODE=1
export PYTHONWARNINGS='ignore'
# more permissive:
# export PYTHONWARNINGS='default,ignore:Not importing directory:ImportWarning'

#
# Local environment
#

# Syntax highlighting in less
if [[ -n "$LESSOPEN" && -f "/usr/local/bin/lesspipe.sh" ]]; then
  export LESSOPEN="|/usr/local/bin/lesspipe.sh %s" LESS_ADVANCED_PREPROCESSOR=1
fi

# base16/tinted
export TINTED_SHELL_ENABLE_BASE16_VARS=1
export BASE16_THEME_DEFAULT='oceanicnext'
export BASE16_SHELL_PATH="$HOME/.dotfiles/base16-shell"
# Disable base16-fzf because Tilix doesn't correctly set the shell background (but it does set the base16-fzf background)
# export BASE16_FZF_PATH="$HOME/.dotfiles/base16-fzf"

# virtualenvwrapper / pyenv-virtualenv / pyenv/virtualenvwrapper
# prezto python module does the rest of the initialization
export PROJECT_HOME="$HOME/dev"
export WORKON_HOME="$HOME/.virtualenvs"

# Hide venv in prompt, prezto already shows it
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

# ripgrep (rg)
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

# homebrew
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
export HOMEBREW_NO_INSTALL_UPGRADE=1

# fzf
export FZF_CTRL_R_OPTS="--no-sort --preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"

if [ -f "$HOME/.environ.local" ]; then
    source "$HOME/.environ.local"
fi
