#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
# Python
#
# See: http://platform-guild.readthedocs.io/en/latest/language-guides/python/development.html
#

export PYTHONDONTWRITEBYTECODE=1
export PYTHONWARNINGS='default,ignore:Not importing directory:ImportWarning'

#
# Local environment
#

if [ -f "$HOME/.environ.local" ]; then
    source "$HOME/.environ.local"
fi

# Syntax highlighting in less
if [[ -n "$LESSOPEN" && -f "/usr/local/bin/lesspipe.sh" ]]; then
  export LESSOPEN="|/usr/local/bin/lesspipe.sh %s" LESS_ADVANCED_PREPROCESSOR=1
fi
