#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Customize to your needs...
# ==========================
#

# Interpret "^" literally, not as EXTENDED_GLOB glob inversion.
# Allows stuff like 'git diff HEAD^'
# https://github.com/robbyrussell/oh-my-zsh/issues/449
unsetopt nomatch

# http://stackoverflow.com/q/14348995
if [ -n "$PS1" ]; then
    # This shell is interactive
    # Ctrl-S and Ctrl-Q is normally for flow control, that feature
    # and to allow those shortcuts to be used in apps
    stty -ixon
fi

# Setup aliases
if [ -f "$HOME/.aliases" ]; then
    source "$HOME/.aliases"
fi

# base16 shell themes -- https://github.com/chriskempson/base16-shell
if [ -n "$PS1" ] && [ -s $HOME/.dotfiles/base16-shell/ ]; then
    eval "$($HOME/.dotfiles/base16-shell/profile_helper.sh)"
fi

# Virtualenvwrapper -- https://virtualenvwrapper.readthedocs.io
if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
    export WORKON_HOME="$HOME/.virtualenvs"
    source /usr/local/bin/virtualenvwrapper.sh
fi

# fzf fuzzy finder -- https://github.com/junegunn/fzf
if [ -f "$HOME/.fzf.zsh" ]; then
  source "$HOME/.fzf.zsh"
fi

# iTerm2 shell integration
if [ -f "${HOME}/.iterm2_shell_integration.zsh" ]; then
  source "${HOME}/.iterm2_shell_integration.zsh"
fi

# Google Cloud SDK (gcloud) auto-completions -- installed with `brew cask install google-cloud-sdk`
if [ -f '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc' ]; then
  source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
fi
if [ -f '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc' ]; then
  source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
fi
