#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Customize to your needs...
# ==========================
#

# http://stackoverflow.com/q/14348995
if [ -n "$PS1" ]; then
    # This shell is interactive
    # Ctrl-S and Ctrl-Q is normally for flow control, that feature
    # and to allow those shortcuts to be used in apps
    stty -ixon
fi

# Setup aliases
if [ -f "$HOME/.aliases" ]; then
    source "$HOME/.aliases"
fi

# base16 shell themes -- https://github.com/chriskempson/base16-shell
if [ -n "$PS1" ] && [ -s $HOME/.dotfiles/base16-shell/ ]; then
    eval "$($HOME/.dotfiles/base16-shell/profile_helper.sh)"
fi

# Virtualenvwrapper -- https://virtualenvwrapper.readthedocs.io
if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
    export WORKON_HOME="$HOME/.virtualenvs"
    source /usr/local/bin/virtualenvwrapper.sh
fi
