#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
  if [ -f "$HOME/.zpreztorc.local" ]; then
      source "$HOME/.zpreztorc.local"
  fi
fi

#
# Customize to your needs...
# ==========================
#

# Interpret "^" literally, not as EXTENDED_GLOB glob inversion.
# Allows stuff like 'git diff HEAD^'
# https://github.com/robbyrussell/oh-my-zsh/issues/449
unsetopt nomatch

# http://stackoverflow.com/q/14348995
if [ -n "$PS1" ]; then
    # This shell is interactive
    # Ctrl-S and Ctrl-Q is normally for flow control, disable
    # that feature to allow those shortcuts to be used in apps
    stty -ixon
fi

# Setup aliases
if [ -f "$HOME/.aliases" ]; then
    source "$HOME/.aliases"
fi

# base16 shell themes -- https://github.com/chriskempson/base16-shell
if [ -n "$PS1" ] && [ -s $HOME/.dotfiles/base16-shell/ ]; then
    eval "$($HOME/.dotfiles/base16-shell/profile_helper.sh)"

    if [ -n "$BASE16_THEME" ] && [ -f "$HOME/.dotfiles/base16-fzf/bash/$BASE16_THEME.config" ]; then
      source "$HOME/.dotfiles/base16-fzf/bash/$BASE16_THEME.config"
    fi
fi

# fzf fuzzy finder -- https://github.com/junegunn/fzf
if [ -f "$HOME/.fzf.zsh" ]; then
  source "$HOME/.fzf.zsh"
fi

# iTerm2 shell integration
if [ -f "${HOME}/.iterm2_shell_integration.zsh" ]; then
  source "${HOME}/.iterm2_shell_integration.zsh"
fi

# Google Cloud SDK (gcloud) auto-completions -- installed with `brew cask install google-cloud-sdk`
if [ -f '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc' ]; then
  source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
fi
if [ -f '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc' ]; then
  source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
fi

# tag - Tag your ag matches -- https://github.com/aykamko/tag
if (( $+commands[tag] )); then
  export TAG_SEARCH_PROG=ag  # replace with rg for ripgrep
  tag() { command tag "$@"; source ${TAG_ALIAS_FILE:-/tmp/tag_aliases} 2>/dev/null }
  alias ag=tag  # replace with rg for ripgrep
fi

if (( $+commands[commitihag] )); then
  commitihag
fi

# fzf/fasd integration -- https://github.com/junegunn/fzf/wiki/examples
if (( $+commands[fzf] && $+functions[fasd] )); then
  # fasd & fzf change directory - open best matched file using `fasd` if given
  # argument, filter output of `fasd` using `fzf` else.
  v() {
      [ $# -gt 0 ] && fasd -f -e ${EDITOR} "$*" && return
      local file
      file="$(fasd -Rfl "$1" | fzf -1 -0 --no-sort +m)" && ${EDITOR} "${file}" || return 1
  }
  # fasd & fzf change directory - jump using `fasd` if given argument, filter
  # output of `fasd` using `fzf` else.
  _fzf_j() {
      [ $# -gt 0 ] && fasd_cd -d "$*" && return
      local dir
      dir="$(fasd -Rdl "$1" | fzf -1 -0 --no-sort +m)" && cd "${dir}" || return 1
  }
  alias j=_fzf_j
fi

if (( $+commands[jenv] )); then
  export PATH="$HOME/.jenv/bin:$PATH"
  eval "$(jenv init -)"
fi
